# Setup
title:        Victor Melo\'s Computational World
tagline:      Topics of computer science for undergraduate students
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Victor S. Melo
  url:        http://victormelo.com.br 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
